"""add_ai_advice_v2_fields

Revision ID: 1f8c49fb620f
Revises: fb5b3ac173dc
Create Date: 2026-05-18 14:01:17.232136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8c49fb620f'
down_revision: Union[str, Sequence[str], None] = 'fb5b3ac173dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    columns = {col["name"] for col in sa.inspect(bind).get_columns("ai_advices")}
    with op.batch_alter_table("ai_advices") as batch_op:
        if "context_json" not in columns:
            batch_op.add_column(sa.Column('context_json', sa.Text(), nullable=True))
        if "structured_output" not in columns:
            batch_op.add_column(sa.Column('structured_output', sa.Text(), nullable=True))
        if "prompt_version" not in columns:
            batch_op.add_column(sa.Column('prompt_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_advices', 'prompt_version')
    op.drop_column('ai_advices', 'structured_output')
    op.drop_column('ai_advices', 'context_json')
    # ### end Alembic commands ###
