"""add_fund_tags_table

Revision ID: 8b2107c04b2f
Revises: 8f33b62c3161
Create Date: 2026-05-18 15:29:28.897444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2107c04b2f'
down_revision: Union[str, Sequence[str], None] = '8f33b62c3161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "fund_tags" not in tables:
        op.create_table('fund_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('fund_code', sa.String(length=10), nullable=False),
        sa.Column('tag_type', sa.String(length=20), nullable=False, comment='industry/theme/style/risk'),
        sa.Column('tag_name', sa.String(length=50), nullable=False, comment='标签名，如 半导体/AI算力/成长/高'),
        sa.Column('tag_value', sa.Float(), nullable=True, comment='暴露权重 0-1，用于聚合计算'),
        sa.Column('source', sa.String(length=10), nullable=True, comment='ai/manual'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['fund_code'], ['funds.fund_code'], ),
        sa.PrimaryKeyConstraint('id')
        )
    index_names = {idx["name"] for idx in sa.inspect(bind).get_indexes("fund_tags")}
    if "ix_fund_tag_code_type" not in index_names:
        op.create_index('ix_fund_tag_code_type', 'fund_tags', ['fund_code', 'tag_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fund_tag_code_type', table_name='fund_tags')
    op.drop_table('fund_tags')
    # ### end Alembic commands ###
