"""initial

Revision ID: fb5b3ac173dc
Revises:
Create Date: 2026-05-13 14:02:16.793335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5b3ac173dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "capital_flows" in tables:
        index_names = {idx["name"] for idx in inspector.get_indexes("capital_flows")}
        if "idx_capital_flow_date_type" not in index_names:
            op.create_index('idx_capital_flow_date_type', 'capital_flows', ['flow_date', 'flow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_capital_flow_date_type', table_name='capital_flows')
    # ### end Alembic commands ###
